import fs from 'node:fs';
import path from 'node:path';
import type { Rule } from '@vue-doctor/core';
import { allRules } from '@vue-doctor/rules';
import { TOOL_VERSION } from '../version.js';

const CURSOR_RULES_DIR = '.cursor/rules';
const CURSOR_RULE_FILE = 'vue-doctor.mdc';

const severityLabel = (severity: Rule['severity']): string => {
  if (severity === 'error') {
    return 'error (fix first)';
  }

  if (severity === 'warn') {
    return 'warning';
  }

  return 'info';
};

const formatRuleSection = (rule: Rule): string => {
  return `- **\`${rule.id}\`** (${severityLabel(rule.severity)}, ${rule.category}) — ${rule.description}`;
};

const buildCursorRuleContent = (rules: Rule[]): string => {
  const errorRules = rules.filter((rule) => rule.severity === 'error');
  const warnRules = rules.filter((rule) => rule.severity === 'warn');
  const infoRules = rules.filter((rule) => rule.severity === 'info');

  const sections = [
    '---',
    'description: Vue Doctor rules — prevent AI-generated Vue anti-patterns',
    'globs: **/*.{vue,ts,tsx}',
    'alwaysApply: false',
    '---',
    '',
    '# Vue Doctor Coding Rules',
    '',
    `Generated by vue-doctor v${TOOL_VERSION}. Run \`npx @vue-doctor/cli .\` to scan.`,
    '',
    'When writing or editing Vue 3 + TypeScript code, follow these rules so scans stay clean.',
    '',
    '## Fix priority',
    '',
    '1. Fix **errors** first — they block CI and drop the health score the most.',
    '2. Then **warnings** — architecture and maintainability debt.',
    '3. **Info** items last — style and modernization hints.',
    '',
  ];

  if (errorRules.length > 0) {
    sections.push('## Errors', '', ...errorRules.map(formatRuleSection), '');
  }

  if (warnRules.length > 0) {
    sections.push('## Warnings', '', ...warnRules.map(formatRuleSection), '');
  }

  if (infoRules.length > 0) {
    sections.push('## Info', '', ...infoRules.map(formatRuleSection), '');
  }

  sections.push(
    '## Architecture patterns',
    '',
    '- Keep API calls in composables or Pinia actions, not in `views/` or `pages/`.',
    '- Use `<script setup lang="ts">` for new components.',
    '- Split oversized composables (>150 lines) and components (>300 lines).',
    '- Always add `:key` on `v-for` items.',
    '',
    '## After AI edits',
    '',
    'Run `npx @vue-doctor/cli .` before committing. In CI, use `--fail-below 70` or the GitHub Action.',
    '',
  );

  return sections.join('\n');
};

export const runInstallCommand = async (targetDirectory: string): Promise<number> => {
  const root = path.resolve(targetDirectory);
  const rulesDir = path.join(root, CURSOR_RULES_DIR);
  const rulePath = path.join(rulesDir, CURSOR_RULE_FILE);

  if (!fs.existsSync(root)) {
    process.stderr.write(`Directory not found: ${root}\n`);
    return 2;
  }

  fs.mkdirSync(rulesDir, { recursive: true });
  fs.writeFileSync(rulePath, buildCursorRuleContent(allRules), 'utf-8');

  process.stdout.write(`Created ${path.relative(root, rulePath).replace(/\\/g, '/')}\n`);
  return 0;
};
